import compression from 'compression';
import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import morgan from 'morgan';
import { config } from './config.js';
import adminRoutes from './routes/adminRoutes.js';
import authRoutes from './routes/authRoutes.js';
import botRoutes from './routes/botRoutes.js';
import movementRoutes from './routes/movementRoutes.js';
import periodRoutes from './routes/periodRoutes.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';

export const app = express();
app.use(helmet());
app.use(cors({ origin: config.corsOrigin, credentials: true }));
app.use(compression());
app.use(express.json({ limit: '2mb' }));
app.use(rateLimit({ windowMs: 60_000, limit: 180 }));
app.use(morgan('combined'));
app.get('/health', (req, res) => res.json({ ok: true, env: config.env }));
app.use('/api/auth', authRoutes);
app.use('/api', movementRoutes);
app.use('/api', periodRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api', botRoutes);
app.use(notFound);
app.use(errorHandler);
